# Generated by Django 2.1.4 on 2018-12-27 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_lc',
            name='aa',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='bb',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='cc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='dd',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='ee',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='ff',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='gg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='hh',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='ii',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='jj',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='kk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='ll',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='mm',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='nn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='oo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract_ci',
            name='owner',
            field=models.ForeignKey(default='SOME_STRING', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Member'),
        ),
        migrations.AlterField(
            model_name='contract_lc',
            name='contract_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contract_lc',
            name='contractname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contract_lc',
            name='filename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract_lc',
            name='sha256',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract_lc',
            name='share1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract_lc',
            name='share2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract_lc',
            name='share3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract_lc',
            name='share4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
