# Generated by Django 2.1.4 on 2018-12-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181227_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract_lc',
            name='aa',
        ),
        migrations.RemoveField(
            model_name='contract_lc',
            name='bb',
        ),
        migrations.RemoveField(
            model_name='contract_lc',
            name='cc',
        ),
        migrations.RemoveField(
            model_name='contract_lc',
            name='dd',
        ),
        migrations.RemoveField(
            model_name='contract_lc',
            name='ee',
        ),
        migrations.RemoveField(
            model_name='contract_lc',
            name='ff',
        ),
        migrations.RemoveField(
            model_name='contract_lc',
            name='gg',
        ),
        migrations.RemoveField(
            model_name='contract_lc',
            name='hh',
        ),
        migrations.RemoveField(
            model_name='contract_lc',
            name='ii',
        ),
        migrations.RemoveField(
            model_name='contract_lc',
            name='jj',
        ),
        migrations.RemoveField(
            model_name='contract_lc',
            name='kk',
        ),
        migrations.RemoveField(
            model_name='contract_lc',
            name='ll',
        ),
        migrations.RemoveField(
            model_name='contract_lc',
            name='mm',
        ),
        migrations.RemoveField(
            model_name='contract_lc',
            name='nn',
        ),
        migrations.RemoveField(
            model_name='contract_lc',
            name='oo',
        ),
        migrations.AddField(
            model_name='contract_lcr',
            name='aa',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lcr',
            name='bb',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lcr',
            name='cc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lcr',
            name='dd',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lcr',
            name='ee',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lcr',
            name='ff',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lcr',
            name='gg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lcr',
            name='hh',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lcr',
            name='ii',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lcr',
            name='jj',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lcr',
            name='kk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lcr',
            name='ll',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lcr',
            name='mm',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lcr',
            name='nn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lcr',
            name='oo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
