# Generated by Django 2.1.4 on 2018-12-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181227_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract_lcr',
            old_name='aa',
            new_name='a',
        ),
        migrations.RenameField(
            model_name='contract_lcr',
            old_name='bb',
            new_name='b',
        ),
        migrations.RenameField(
            model_name='contract_lcr',
            old_name='ff',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='contract_lcr',
            old_name='cc',
            new_name='d',
        ),
        migrations.RenameField(
            model_name='contract_lcr',
            old_name='dd',
            new_name='e',
        ),
        migrations.RenameField(
            model_name='contract_lcr',
            old_name='ee',
            new_name='f',
        ),
        migrations.RenameField(
            model_name='contract_lcr',
            old_name='gg',
            new_name='g',
        ),
        migrations.RenameField(
            model_name='contract_lcr',
            old_name='hh',
            new_name='h',
        ),
        migrations.RenameField(
            model_name='contract_lcr',
            old_name='ii',
            new_name='i',
        ),
        migrations.RenameField(
            model_name='contract_lcr',
            old_name='jj',
            new_name='j',
        ),
        migrations.RenameField(
            model_name='contract_lcr',
            old_name='kk',
            new_name='k',
        ),
        migrations.RenameField(
            model_name='contract_lcr',
            old_name='ll',
            new_name='l',
        ),
        migrations.RenameField(
            model_name='contract_lcr',
            old_name='mm',
            new_name='m',
        ),
        migrations.RenameField(
            model_name='contract_lcr',
            old_name='nn',
            new_name='n',
        ),
        migrations.RenameField(
            model_name='contract_lcr',
            old_name='oo',
            new_name='o',
        ),
    ]
