# Generated by Django 2.1.4 on 2018-12-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181227_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_lcr',
            name='Created',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
