# Generated by Django 2.1.4 on 2018-12-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contract_lcr_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_bl',
            name='Created',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_bl',
            name='a',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_bl',
            name='b',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_bl',
            name='c',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_bl',
            name='d',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_bl',
            name='e',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_bl',
            name='f',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_bl',
            name='g',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_bl',
            name='h',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_bl',
            name='i',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_bl',
            name='j',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_ci',
            name='Created',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_ci',
            name='a',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_ci',
            name='b',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_ci',
            name='c',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_ci',
            name='d',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_ci',
            name='e',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_ci',
            name='f',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_ci',
            name='g',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_ci',
            name='h',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_ci',
            name='i',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_ci',
            name='j',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_ci',
            name='k',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_ci',
            name='l',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_ci',
            name='m',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_ci',
            name='n',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_ci',
            name='o',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_ci',
            name='p',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_ci',
            name='q',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_ci',
            name='r',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_do',
            name='Created',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_do',
            name='a',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_do',
            name='b',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_do',
            name='c',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_do',
            name='d',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_do',
            name='e',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_do',
            name='f',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_do',
            name='g',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='Created',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='a',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='aa',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='b',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='bb',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='c',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='cc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='d',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='dd',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='e',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='ee',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='f',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='ff',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='g',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='gg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='h',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='i',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='j',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='k',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='l',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='m',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='n',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='o',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='p',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='q',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='r',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='s',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='t',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='x',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='y',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_lc',
            name='z',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_sr',
            name='Created',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_sr',
            name='a',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_sr',
            name='b',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_sr',
            name='c',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_sr',
            name='d',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_sr',
            name='e',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_sr',
            name='f',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_sr',
            name='g',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_sr',
            name='h',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_sr',
            name='i',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_sr',
            name='j',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_sr',
            name='k',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_sr',
            name='l',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_sr',
            name='m',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_sr',
            name='n',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract_sr',
            name='o',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
